# Generated by Django 5.1.3 on 2025-02-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalChatbot', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
