# Generated by Django 5.1.3 on 2025-03-06 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalChatbot', '0005_client_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='filled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
